name: otomasi deploy server

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/be-app:latest
    - 
      name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          docker stop ${{ secrets.CNAME }}
          docker rm ${{ secrets.CNAME }}
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/be-app:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/be-app:latest
          docker run -d -p 80:80 \
              -e Username=${{ secrets.DB_USERNAME }} \
              -e Password=${{ secrets.DB_PASSWORD }} \
              -e Host=${{ secrets.DB_HOST }} \
              -e Port=${{ secrets.DB_PORT }} \
              -e Name=${{ secrets.DB_NAME }} \
              -e JWTSecret=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/be-app:latest