// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	book "github.com/ALTA-BE17/Rest-API-Clean-Arch-Test/features/book"
	mock "github.com/stretchr/testify/mock"
)

// BookService is an autogenerated mock type for the BookService type
type BookService struct {
	mock.Mock
}

// InsertBook provides a mock function with given fields: userId, request
func (_m *BookService) InsertBook(userId uint, request book.Core) (book.Core, error) {
	ret := _m.Called(userId, request)

	var r0 book.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, book.Core) (book.Core, error)); ok {
		return rf(userId, request)
	}
	if rf, ok := ret.Get(0).(func(uint, book.Core) book.Core); ok {
		r0 = rf(userId, request)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	if rf, ok := ret.Get(1).(func(uint, book.Core) error); ok {
		r1 = rf(userId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBooks provides a mock function with given fields:
func (_m *BookService) ListBooks() ([]book.Core, error) {
	ret := _m.Called()

	var r0 []book.Core
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]book.Core, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []book.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBook provides a mock function with given fields: userId, request
func (_m *BookService) UpdateBook(userId uint, request *book.Core) (book.Core, error) {
	ret := _m.Called(userId, request)

	var r0 book.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *book.Core) (book.Core, error)); ok {
		return rf(userId, request)
	}
	if rf, ok := ret.Get(0).(func(uint, *book.Core) book.Core); ok {
		r0 = rf(userId, request)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	if rf, ok := ret.Get(1).(func(uint, *book.Core) error); ok {
		r1 = rf(userId, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookService creates a new instance of BookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookService(t mockConstructorTestingTNewBookService) *BookService {
	mock := &BookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
